/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CartCatalogue: typeof import('./src/components/CartCatalogue.vue')['default']
    MenuBar: typeof import('./src/components/MenuBar.vue')['default']
    ProductItem: typeof import('./src/components/ProductItem.vue')['default']
    PurpleModal: typeof import('./src/components/PurpleModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectDrpDown: typeof import('./src/components/SelectDrpDown.vue')['default']
  }
}
