/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/CartPage': RouteRecordInfo<'/CartPage', '/CartPage', Record<never, never>, Record<never, never>>,
    '/CustomerInfoForm': RouteRecordInfo<'/CustomerInfoForm', '/CustomerInfoForm', Record<never, never>, Record<never, never>>,
    '/DeliveryMethod': RouteRecordInfo<'/DeliveryMethod', '/DeliveryMethod', Record<never, never>, Record<never, never>>,
    '/OrderDetails': RouteRecordInfo<'/OrderDetails', '/OrderDetails', Record<never, never>, Record<never, never>>,
    '/OrderPlaced': RouteRecordInfo<'/OrderPlaced', '/OrderPlaced', Record<never, never>, Record<never, never>>,
    '/ProductGrid': RouteRecordInfo<'/ProductGrid', '/ProductGrid', Record<never, never>, Record<never, never>>,
    '/ProductList': RouteRecordInfo<'/ProductList', '/ProductList', Record<never, never>, Record<never, never>>,
    '/UnavailableProduct': RouteRecordInfo<'/UnavailableProduct', '/UnavailableProduct', Record<never, never>, Record<never, never>>,
  }
}
